cc_test(
    name = "span-test",
    size = "small",
    srcs = ["print_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch5/poc4/main:span",
    ],
)
