cc_test(
    name = "animal-test",
    size = "small",
    srcs = ["animal_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch6/poc2/main:animal",
    ],
)
