load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "span",
    srcs = [
    ],
    hdrs = [
        "print.h",
    ],
    copts = ["-std=c++20"],
    visibility = ["//ch5/poc4/test:__pkg__"],
)
