load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "traverse",
    hdrs = [
        "traverse.h",
    ],
    srcs = [
        "traverse.cpp",
    ],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)
