load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "person",
    srcs = [
        "person.cpp",
    ],
    hdrs = [
        "person.h",
    ],
    copts = ["-std=c++20"],
    visibility = ["//ch6/poc1/test:__pkg__"],
)
