load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "shape",
    srcs = [
    ],
    hdrs = [
        "shape.h",
        "circle.h", "ostream_circle_strategy.h",
    ],
    copts = ["-std=c++20"],
    visibility = ["//ch5/poc6/test:__pkg__"],
)
