cc_test(
    name = "variant",
    size = "small",
    srcs = ["variant.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch4/variant/main:print",
    ],
)
