cc_test(
    name = "shape-test",
    size = "small",
    srcs = ["shape_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch6/poc5/main:shape",
    ],
)
