load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "print",
    srcs = [
    ],
    hdrs = [
        "print.h",
    ],
    copts = ["-std=c++20"],
    visibility = ["//ch4/variant/test:__pkg__"],
)
