load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "foo",
    srcs = [
    ],
    hdrs = [
        "foo.h",
    ],
    copts = ["-std=c++20"],
    visibility = ["//ch5/poc5/test:__pkg__"],
)
