cc_test(
    name = "count-lines-test",
    size = "small",
    srcs = ["count_lines_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch01/main:count-lines",
    ],
)
