cc_test(
    name = "person-test",
    size = "small",
    srcs = ["person_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch6/poc1/main:person",
    ],
)
