cc_test(
    name = "traverse-test",
    size = "small",
    srcs = ["traverse_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch6/poc3/main:traverse",
    ],
)
