cc_test(
    name = "item-test",
    size = "small",
    srcs = ["item_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch1/main:item",
    ],
)
