cc_test(
    name = "widget-test",
    size = "small",
    srcs = ["widget_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch2/main:widget",
    ],
)
