/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package etl;

public class App {
    /**
     * This Java source file was generated by the Gradle 'init' task.
     * @return nothing
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * This Java source file was generated by the Gradle 'init' task.
     * @param args
     */
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
