cc_test(
    name = "shape-test",
    size = "small",
    srcs = ["calc_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch5/poc3/main:shape",
    ],
)
