cc_test(
    name = "function-test",
    size = "small",
    srcs = ["function_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//ch5/poc5/main:foo",
    ],
)
