load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "shape",
    hdrs = [
        "shape.h",
        "circle.h", "square.h",
        "cout_drawer.h",
    ],
    srcs = [
        "cout_drawer.cpp",
    ],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)
